# Initialize kernel
/run/initialize

#/control/verbose 0
#/run/verbose 0
#/event/verbose 0
#/tracking/verbose 0
# 
# gamma 6 MeV to the direction (0.,0.,1.)
#
#/gun/particle gamma
#/gun/energy 6 MeV
#
#/run/beamOn 5
# 
# proton 210 MeV to the direction (0.,0.,1.)
#
#/gun/particle proton
#/gun/energy 210 MeV
#/tracking/verbose 0
#

/process/had/rdm/thresholdForVeryLongDecayTime 1.0e+60 year

/gun/particle ion
/gun/ion 27 58 0 0
#/gun/energy 0 MeV
/run/beamOn 252683
